<?php
	define('CONSUMER_KEY', 'REPLACE_WITH_YOUR_KEY_HERE');
	define('CONSUMER_SECRET', 'REPLACE_WITH_YOUR_SECRET_KEY_HERE');
	define('ACCESS_TOKEN', 'REPLACE_WITH_YOUR_TOKEN_HERE');
	define('ACCESS_TOKEN_SECRET', 'REPLACE_WITH_YOUR_TOKEN_SECRET_HERE');
	define('TWITTER_USERNAME', 'REPLACE_WITH_YOUR_TWITTER_USERNAME'); //without @ symbol, example: alternat0r
?>